### ISSUE TITLE
Create process for populating dev db data on rails app startup

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#10]
In our prior grails project, the dev db was set to re-initialize from a static data set upon startup. Implement this in the rails app, or implement another mechanism for giving devs a reasonable local data set.

**Comment by jfhamlin** [comment]
@jjfreund Does this satisfy the need you had in mind? https://github.com/ShelterTechSF/askdarcel-api/blob/master/lib/tasks/populate.rake#L2

`rake db:populate` will delete any existing records and create 20 random categories and 128 random resources with 0-3 associated categories.

**Comment by jfhamlin** [comment]
Moved it to "Done." If there are no other immediate enhancements required, I'll close the issue.
