### ISSUE TITLE
Create process for exporting production db and importing it into dev workstations

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#133]

**Comment by lgarofalo** [comment]
It looks like we could pg_dump and pg_restore to do this

**Comment by richardxia** [comment]
Yep, exactly what I was thinking. I already started working on it earlier this week, and I a branch ready for review now.

**Comment by Maxastuart** [comment]
Please update or close? @lgarofalo @richardxia

**Comment by richardxia** [comment]
I think @cliffcrosland did this recently?

**Comment by cliffcrosland** [comment]
Yep! This is done. The staging database (which is more or less a copy of the production database) can be cloned locally with this command, which appears in the Readme.
```
# Populate the database with a direct copy of the live staging database.
# - Ask technical team for the staging database password.
docker-compose run -e STAGING_DB_PASSWORD=<...> --rm api rake db:setup db:import_staging
```
