### ISSUE TITLE
Revise Categorization

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#205]
Categories should be associated with services only -- resources should aggregate categories from the constituent service

**Comment by richardxia** [comment]
How do we want to deal with the migration of Resources which have categories on prod? The simplest thing to do would be to just drop them, but I don't know what percentage of Services don't have any categories associated with them.

**Comment by richardxia** [comment]
I'm going to move this to milestone 1.10, since this is blocked on the schema changes we are making.
