### ISSUE TITLE
Admin analytics

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#209]
Create basic reports that convey number of resources and services added, change logs filed and approved, and number of resources/services currently active per category. Build a front end to display these reports.

**Comment by twolfe2** [comment]
@jjfreund could we have 2 endpoints for this? 

One for the post workshop stats that would be passed this:
```
start_date: 2017-10-01
end_date: 2017-10-02
```

and return then return the following:
```
{
  change_requests: 221,
  resources_added: 10,
  services_added: 50,
  logs_filed: 300,
  logs_approved: 21
}
```

And another for the category stats that will return something like this:
```
[
  {
    name: "Housing",
    services: 200,
    resources: 43
  }, 
  {
    name: "Health"
    services: 210,
    resources: 34
  }
]
```

**Comment by lgarofalo** [comment]
@twolfe2 I will start working on these endpoints
