### ISSUE TITLE
Create endpoint displaying number of resources and services by category

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#217]

**Comment by lgarofalo** [comment]
GET: /categories/counts
`[
    {
        "name": "Food",
        "services": 44,
        "resources": 44
    },
    {
        "name": "Hygiene",
        "services": 14,
        "resources": 14
    },
    {
        "name": "Medical",
        "services": 105,
        "resources": 105
    },
    {
        "name": "Shelter",
        "services": 24,
        "resources": 24
    },
    {
        "name": "Technology",
        "services": 55,
        "resources": 55
    }
]`
