### ISSUE TITLE
Make factory girl test data more realistic

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#24]
Test data should include new models, and should more accurately resemble data from link-sf.

**Comment by clizzin** [comment]
By the way, Rails includes a concept of "seed data": you can write arbitrary Ruby/Rails code in `db/seeds.rb`, and running the `db:seed` rake task will execute the data.  Useful for starting the database in a certain state when running tests or setting up a new development environment.

**Comment by jfhamlin** [comment]
My understanding of `rake db:seeds` is that it's intended to be used in all environments, including production, and should therefore load data that is required or generally useful for the operation of the service. In our case, for instance, we could seed a database with a set of common categories. Maybe we could switch on environment to include more in development. I'd be interested in getting your perspective on approaches to Rails testing, BTW. Next time we meet in person for ST, maybe.

**Comment by clizzin** [comment]
Ah, I see.  I've only ever used it for development/test and used migrations instead for populating production databases, but I can see why the approach you describe is better.

Re Rails testing: sure, let's discuss next week!
