### ISSUE TITLE
Add Openness to algolia result ranking

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#314]
Default search results should favor Featured, MOHCD Funded, Openness (possibly opens soon too), then Location (then later last_verified_at). 

- adjust Algolia settings to take into account the Open Now attributes

**Comment by jjfreund** [comment]
Update -- we triaged this to favor categories and name for the purposes of Hicham's meeting but it is still not correct.

**Comment by Maxastuart** [comment]
1. Is there any active progress on this?
2. Are there any issues or pulls it's connected with? 
3. Is there a feature requirements doc, or should I make one? 
4. And which of the 5 assignees is the owner? 

I think I know a few people outside the dev team to speak to about this to help move it along, but wanted to ask here first.

**Comment by Maxastuart** [comment]
Feature Spec: 
https://sheltertech.quip.com/o0M1AibTyGmd/Search-Results-Requirements

**Comment by Maxastuart** [comment]
Retitling this issue to reflect that MOHCD ranking and regular interval reindexing have already been accomplished

**Comment by Maxastuart** [comment]
Requested by Barry on July 17th, 2019. Slack me for more details.

**Comment by Maxastuart** [comment]
Breaking apart to https://github.com/ShelterTechSF/askdarcel-web/issues/870

**Comment by Maxastuart** [comment]
Tableing for now - @richardxia has explained it's not easy to pass Algolia the info of whats open when so we'll make do with just the filter option for now
