### ISSUE TITLE
Create new tasks for expanding Swagger (API documentation generator)

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-api#395]
richardxia commented on May 24, 2017:
I think there are several libraries that help you automatically generate documentation for REST APIs, which would be helpful for decoupling frontend and backend development. A few libraries I found from a quick Google search:

https://github.com/Apipie/apipie-rails
https://github.com/zipmark/rspec_api_documentation
https://github.com/lord/slate

If any of these work out, it'd be really cool to have Travis build the docs automatically and push them to GitHub Pages.

**Comment by Maxastuart** [comment]
Lets do it! Sounds like we already have Swagger, will that suffice @richardxia ?

**Comment by richardxia** [comment]
Yeah, Swagger would satisfy that requirement. I don't actually know anything about our current integration with Swagger, and @jjfreund might know better about what has been done and what further improvements we could make.

**Comment by kumquatexpress** [comment]
Howdy! I can take a crack at this given that it's not on the critical path.

**Comment by Maxastuart** [comment]
@kumquatexpress is this as much as we're going to work on it for now? just close if so
