### ISSUE TITLE
Store open and close times in schedule_day table as times

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#399]
Currently, the open and close time are stored as integers, but could be more accurately represented as as times. There is a postgres data type, time, which is used to represent time-of-day (dateless) values. Modify the schedule_day table to use this data type for open and close times.

The day of week is currently a single field in the schedule_day table. This is incorrect -- since open and close times can span one day to another, we should track the open day and close day separately. Add the following four fields to the schedule day table:

open_day character
open_time time
close_day character
close_time time

**Comment by Maxastuart** [comment]
This is perfect! Thanks so much!
