### ISSUE TITLE
Modify search to meet MOHCD launch requirements

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#415]
MOHCD has suggested that we enhance search to favor MOHCD sponsored resources, to allow for individual services and resources to be featured, and to allow for "compound" searches -- first searching by category or keyword, and then filtering by eligibility.

**Comment by Maxastuart** [comment]
Search results in AskDarcel should yield the following (see these reqs at https://www.notion.so/sheltertech/Improve-Search-Indexing-Algolia-e4f53456c8bd4565b9f54f6ab09e811d ):

- These specific resources should appear first in the Algolia search results for their category:
    - [https://sfmohcd.org/sites/default/files/Documents/MOH/SF Housing Resource Guide.pdf](https://sfmohcd.org/sites/default/files/Documents/MOH/SF%20Housing%20Resource%20Guide.pdf)
    - DAHLIA ([www.housing.sfgov.org](http://www.housing.sfgov.org/)) should appear in housing category resources (ideally first)
- These resources should appear first by population (eligibility) search:
    - [https://sfmohcd.org/san-francisco-housing-resource-guide](https://sfmohcd.org/san-francisco-housing-resource-guide)
- Searches should parse terms in the database fields:
    - Name
    - Description
    - Notes
    - Category
    - Eligibility
- Add synonyms to search (i.e. when someone searches bath, shower results will also appear) csv:

    [Search Synonyms](https://www.notion.so/8ed13998dace44f2888af937522052cb)

- Recognize a key term embedded in a phrase
    - It would also be good to include specific and very popular phrases “bed” out of “i need a bed”
    - Use a list of phrases/terms lay people may type in
    - Use a list of phrases/terms case managers or social workers may type in
        - (One of the service provider testers pointed out that the language a social worker might use may be different from lay person, since they already have some idea of what resources fall in what categories (eligibility, etc.))
