### ISSUE TITLE
Modify Search Results to favor "Featured" Orgs & Services (Algolia, Database)

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#417]
Search results should be ordered first by the new "featured," column (with those services and resources with a value of true prioritized) and then by other criteria.

**Comment by quanhuynh** [comment]
@jjfreund @Maxastuart 
This change is made on staging. As soon as production resources has the 'featured' field globally changed to boolean values, this change can roll out there as well.
![Screen Shot 2019-06-02 at 9 16 18 PM](https://user-images.githubusercontent.com/8869737/58775745-ede21880-857b-11e9-9dd2-0aab397856e2.png)

**Comment by Maxastuart** [comment]
We need to go through and tag these orgs/services MOHCD provided so far (I have requested more):
- These specific resources should appear first in the Algolia search results for their category:
    - [https://sfmohcd.org/sites/default/files/Documents/MOH/SF Housing Resource Guide.pdf](https://sfmohcd.org/sites/default/files/Documents/MOH/SF%20Housing%20Resource%20Guide.pdf)
    - DAHLIA ([www.housing.sfgov.org](http://www.housing.sfgov.org/)) should appear in housing category resources (ideally first)
- These resources should appear first by population (eligibility) search:
    - [https://sfmohcd.org/san-francisco-housing-resource-guide](https://sfmohcd.org/san-francisco-housing-resource-guide)

**Comment by Maxastuart** [comment]
Shouldn't have closed this, this isn't complete until "production server resources has the 'featured' field globally changed to boolean values"

**Comment by Maxastuart** [comment]
@quanhuynh @jjfreund can someone confirm that "production server resources has the 'featured' field globally changed to boolean values"?

**Comment by jjfreund** [comment]
In production, there are a few orgs and services correctly tagged as featured and the bulk have been updated as not featured (rather than having a null value). If I recall, this should be sufficient for the Algolia algorithm to work. There are a few records left with null values, which were recently created. We'll need to change the db such that this value defaults to false for new records if not explicitly set; I'll create a separate ticket for that.

**Comment by Maxastuart** [comment]
@jjfreund separate ticket for that ^^ created (api-459)
