### ISSUE TITLE
Modify Algolia search results to favor MOHCD funded services 

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#418]
Right now, the service index in Algolia currently has a denormalized field which represents whether each service is funded by MOHCD -- is_mohcd_funded. Modify the way in which search results are ordered such that MOHCD funded services are prioritized after featured services and before other services.

**Comment by quanhuynh** [comment]
@jjfreund @Maxastuart 
Change made on both staging and production. Looks like this on search page now. You guys can verify with a quick look on the search page of askdarcel
![Screen Shot 2019-06-02 at 9 15 53 PM](https://user-images.githubusercontent.com/8869737/58775816-49140b00-857c-11e9-97ef-c717b7498d54.png)
