### ISSUE TITLE
Create "Hours Unknown/Call for Hours" feature

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-api#442]
- Add a flag to the database indicating that an organization's hours are "unknown"
- Modify the UI on Search Results such that in those cases "Call for Hours" is displayed rather than open/closed
- Modify the UI on Org/Service pages such that in those cases "Call for Hours" is displayed rather than an actual set of hours.
- Set the Organization "Q Foundation" to this status

**Comment by drcaramelsyrup** [comment]
@Maxastuart : Is this for hours that are empty? Or should we be able to mark orgs, even with some hour / time information, with this flag?

**Comment by Maxastuart** [comment]
In the long run, this should be a checkbox that greys out the Hours section on the Edit page. In the short term we don't care what hours are in or not, it's just a flag we can add via the database backend and we don't immediately need the checkbox frontend (there are other urgent tasks if you finish the flagging of Q foundation) @drcaramelsyrup
