### ISSUE TITLE
Tag MORE Featured Orgs/Services

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-api#444]
Original #439:
"We need to go through and tag, on the production database, orgs/services MOHCD provided to be featured at the top of search results for given categories and eligibilities so far (I have requested more):

These specific resources should appear first in the Algolia search results for their category:
https://sfmohcd.org/sites/default/files/Documents/MOH/SF Housing Resource Guide.pdf
DAHLIA (www.housing.sfgov.org) should appear in housing category resources (ideally first)
These resources should appear first by population (eligibility) search:
https://sfmohcd.org/san-francisco-housing-resource-guide "

Tagged already Organizations: (918,487,408,917,489,580,90,526,18,867,869,398,472,745,390,325,580,465,841,887,4,602,536,172,264,202,184,865,213,32,204,295,343,813,328,366,560,368,161)
and Services: 
(2271,2272,1711,2565)

Still need to tag or deal with (email sent to Julie & Barry and mtg scheduled for Tues 8/20/2019): 

"Displaced Tenant Housing Preference" & "Housing Email Alert" MOHCD services not found, add & tag? 
"HAP" tag Org or Service? 
"La Raza Centro Legal" tag Org or Service? 
"San Francisco Housing Development Corporation" tag Org or Service? 
"MEDA" tag Org or Service? 
"SFLGBT Center" tag Org or Service? 
"Huckleberry Youth Programs" tag Org or Service? 
"Bill Sorro Housing Program" missing Org, add & tag? 
"Bayanihan Equity Center" missing Org, add & tag? 
"SF Domestic Violence Hotline/Consortium" missing Org, add & tag? 
"AIDS Housing Alliance" missing Org, add & tag? 
"San Francisco AIDS Foundation" missing Org, add & tag?
"Riley Center" duplicates (3-4)?

**Comment by schroerbrian** [comment]
No longer relevant
