### ISSUE TITLE
Service Net data trust metadata

### ISSUE THREAD

**Issue by drcaramelsyrup** [ShelterTechSF/askdarcel-api#454]
As per Benetech Service Net's recent request, we'd like to add more metadata about our updates.

Specifically their asks are, for each record, we should store:
the most recent *partial update*'s
- date / time
- first + last name of updater (optional for now, but I think this will be useful for listing resource managers' names once we have ShelterNet in place)

and the most recent *complete update*'s
- date / time
- first + last name of updater
- primary source enum, i.e. where the information for the update came from. (IMO these values should be: "website", "social_media", "verbal", "email", "paper", "third_party")

When Benetech pulls the API for a resource / service, that record should also include information about these fields. Alternatively, I think it'd be fine if we wanted Benetech to hit a different endpoint for this metadata.

Because as of Sep 21 2019 we don't have a full idea of what defines a "complete" vs "partial" review, I think that we should be storing all three metadata fields for any change request, along with an array listing which fields changed. (I believe we already have timestamp information for each change request.)

Storing this metadata in each change request may make it more difficult to present the data in the API, but this way we'll have a full history and, if we wanted, could even surface the last time any field has been updated, and by whom.

**Comment by Maxastuart** [comment]
moved to https://app.clubhouse.io/sheltertech/epic/18/data-trust-metadata

**Comment by richardxia** [comment]
It doesn't look like we are currently doing any syncs with Benetech at the moment, or at least it doesn't look like any of the people active at ShelterTech that I asked know about it, so I'm going to close this as stale.
