### ISSUE TITLE
Implement hierarchical categorization

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#455]
Currently, our category structure is flat. We would like to revise this and have categories be tagged as children of other categories so that searches for one category can be refined as searches for the category's more specific children. Each category should be able to be a child of more than one parent.

First, we should modify the data model to capture the many-many relationship between parent and child categories. We should then modify our existing data to capture the relationships between categories and expose these relationships via our API.

When this is complete, we can then add a UI for refining searches as described above.

Spec of Hierarchy relationships available here, on the 2nd sheet labeled Categories (hierarchy): 
https://docs.google.com/spreadsheets/d/1HxhRMuWcZkkjPWqXawpBZmClE8fVYFiium8fSWD4tQk/edit#gid=679613574

**Comment by schroerbrian** [comment]
This is completed
