### ISSUE TITLE
Add REST endpoints for each domain object included in current Resources call

### ISSUE THREAD

**Issue by lelandg559** [ShelterTechSF/askdarcel-api#52]
It's better design and apparently react works much better with that (makes sense)

Will include all current objects included in the resources call

**Comment by jfhamlin** [comment]
How would the clients use the new endpoints?

**Comment by lelandg559** [comment]
The structure of the react (module?) actually favors individual resource object calls, as the UI components are modularized and reused, it favors loading only what its responsible for given its greater context.

Front end/avneet brought this up to me as something that would make things easier for them (and is a better design)

I wont modify the large resources call for now though, only add the new endpoints for contained objects.

**Comment by lelandg559** [comment]
I'll verify but I believe each scenario is just GET using the parent objects ID  resource/resourceid/services etc

**Comment by jfhamlin** [comment]
Interesting. Let's talk about this one at Wednesday's meeting. Lots of round trips to fetch small bits of data won't be very efficient. I'm not that familiar with React, but I don't think it forces a particular backend API structure on us. Every React component (if I'm understanding the level of granularity correctly) shouldn't need its own network request.

**Comment by lelandg559** [comment]
Makes sense, yea we can talk about it then.

**Comment by jjfreund** [comment]
After further conversations, we decided not to do this.
