### ISSUE TITLE
Add first take on search functionality, which searches for categories by keywords 

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-api#56]
TBD

**Comment by jfhamlin** [comment]
I'd meant to talk about this in our last meeting. We already have a way for users to view resources by category: the category links shown prominently below the search bar. I think a more impactful first take at search would be to search the columns of resources and/or services, specifically the name and description fields. We can search the `name` column of category associations too, which will accomplish (in part) the goal defined here. I'd like to discuss the further goal of searching by synonyms and related terms. I think there may be simpler and more general ways to implement that.
