### ISSUE TITLE
Add UCSF site and associate all UCSF resources with the new site.

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#618]
Add a new record in the "sites" table for UCSF. This record should be added to the production database via SQL and to the local development db via modifying the rake task used to populate the db.

Existing production resources associated with the UCSF project should be manually associated with the new site. The dev db population script should be modified such that  a subset of the randomly created development resources are associated with the new site.

**Comment by schroerbrian** [comment]
No longer needed. Closing.
