### ISSUE TITLE
Add parent-child inheritance for eligibilities.

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#619]
Allow for parent-child inheritance between eligibilities. Add a join table eligibility_relationships between eligibilities and eligibilities with two foreign keys both to the eligibility table (parent_id and child_id). See the category_relationships table for an example of this.

Modify the script that populates the local database to include the eligibilities needed for the new UCSF pathway. A list of these eligibilities can be found here:

https://www.figma.com/file/HUTUyVuJf8lctj5fAFIY32/Personas-and-Journey-Map?node-id=3613%3A3947

**Comment by schroerbrian** [comment]
By the way, I have posted a comment on the Figma designs asking Fred and Dongyeon if the eligibilities are the same across the three UCSF resources (Substance Abuse, Mental Health, and Shelter.
