### ISSUE TITLE
Create data model for breaking news section

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#627]
Add a "news" model which will be used to populate the top of the site with breaking news. The news model will have the following properties:

Headline: Short description summarizing the new development.
Effective_Date: The date of the announcement.
Body: The body of the announcement. This should be long enough to consist of multiple paragraphs and can include markdown.
Priority: Integer. Used to determine sort order of results.
Expiration_Date: Used to determine when the news items will no longer be displayed on the site.

**Comment by richardxia** [comment]
Closing, since this was done a while ago.
