### ISSUE TITLE
Research general "responsiveness" issues

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#90]
We may want to implement logging of request times, and research ways in which to attribute time taken to db queries etc.

**Comment by jfhamlin** [comment]
Yeah, piping all request logs somewhere is going to be a must-have.

**Comment by jfhamlin** [comment]
I filed https://github.com/ShelterTechSF/cloudformation/issues/10 to set up something for shipping logs. There may be work needed in this project to complete that, but I think we can file more specific issues when we get to it. I'm not positive there are actually pressing performance issues to investigate here, so can this issue be closed?
